calibrated: false
planning_segments:
- id: p_to_qr
  direction: forward
  start_id: p_start
  end_id: a_task_observe
  through_ids: []
- id: qr_to_vlm
  direction: forward
  start_id: a_task_observe
  end_id: c_corner_1
  through_ids:
  - via_1
  - via_2
  - via_3
  - via_6
- id: return_to_p
  direction: forward
  start_id: c_corner_1
  end_id: p_finish
  through_ids:
  - via_4
  - via_5
  - via_7
waypoints:
- id: p_start
  frame_id: odom_combined
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  task: start
  direction: forward
  goal_profile: standard
- id: a_task_observe
  frame_id: odom_combined
  pose:
    position:
      x: 3.816402681160821
      y: 0.8413601197275552
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.47715876025960835
      w: 0.8788171126619654
  task: qr
  direction: forward
  goal_profile: precise
  heading_mode: locked
- id: via_1
  frame_id: odom_combined
  pose:
    position:
      x: 1.993278937419563
      y: 1.6677023005148015
      z: 0.0
  task: via
  direction: forward
  goal_profile: standard
- id: via_2
  frame_id: odom_combined
  pose:
    position:
      x: 2.033889545441502
      y: 2.675583012789576
      z: 0.0
  task: via
  direction: forward
  goal_profile: standard
- id: via_3
  frame_id: odom_combined
  pose:
    position:
      x: 3.3682610903314036
      y: 3.0314890001608763
      z: 0.0
  task: via
  direction: forward
  goal_profile: standard
- id: via_6
  frame_id: odom_combined
  pose:
    position:
      x: 3.353935458896397
      y: 4.04144601632883
      z: 0.0
  task: via
  direction: forward
  goal_profile: standard
- id: c_corner_1
  frame_id: odom_combined
  pose:
    position:
      x: 0.5834193626471001
      y: 4.115308972007723
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0
  task: vlm
  direction: forward
  goal_profile: precise
  heading_mode: locked
- id: via_4
  frame_id: odom_combined
  pose:
    position:
      x: 0.5870007705058516
      y: 3.0050725357947243
      z: 0.0
  task: via
  direction: forward
  goal_profile: standard
- id: via_5
  frame_id: odom_combined
  pose:
    position:
      x: 2.0303081375827503
      y: 2.668420197072073
      z: 0.0
  task: via
  direction: forward
  goal_profile: standard
- id: via_7
  frame_id: odom_combined
  pose:
    position:
      x: 2.0088196904302404
      y: 1.7730682323841704
      z: 0.0
  task: via
  direction: forward
  goal_profile: standard
- id: p_finish
  frame_id: odom_combined
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
  task: return
  direction: forward
  goal_profile: standard
