#!/bin/bash
# Rebuild the physical navigation stack only after source/config changes.
set -euo pipefail

WORKSPACE=/home/sunrise/ros2_ws
SOURCE_ENV="$WORKSPACE/scripts/source_env.sh"
COLCON_PARALLEL_WORKERS=8
COMPETITION_ENV_SNAPSHOT="$WORKSPACE/.smartcar_competition_env.sh"

write_competition_env_snapshot() {
  # Keep the fast path limited to variables owned by the ROS setup hooks. DDS
  # and domain settings remain under the operator's environment at runtime.
  local temporary_file="${COMPETITION_ENV_SNAPSHOT}.$$"
  local -a environment_variables=(
    AMENT_PREFIX_PATH
    CMAKE_PREFIX_PATH
    COLCON_PREFIX_PATH
    LD_LIBRARY_PATH
    PATH
    PYTHONPATH
    ROS_DISTRO
    ROS_LOCALHOST_ONLY
    ROS_PYTHON_VERSION
    ROS_VERSION
  )

  (
    SMARTCAR_COMPETITION_FAST_ENV=0
    set +u
    source "$SOURCE_ENV"
    set -u
    umask 077
    {
      printf '%s\n' '# Generated by nav_prepare.sh; do not edit.'
      local name
      for name in "${environment_variables[@]}"; do
        if [[ -v "$name" ]]; then
          printf 'export %s=%q\n' "$name" "${!name}"
        else
          printf 'unset %s\n' "$name"
        fi
      done
    } > "$temporary_file"
    chmod 600 "$temporary_file"
    mv -f "$temporary_file" "$COMPETITION_ENV_SNAPSHOT"
  )
}

SMARTCAR_COMPETITION_FAST_ENV=0
set +u
source "$SOURCE_ENV"
set -u
cd "$WORKSPACE"

bash "$WORKSPACE/scripts/ros_cleanup.sh"

colcon build --symlink-install \
  --parallel-workers "$COLCON_PARALLEL_WORKERS" \
  --packages-up-to smartcar_bringup smartcar_vision smartcar_tools \
  --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  --allow-overriding ackermann_msgs smartcar_interfaces smartcar_safety smartcar_nav2 smartcar_task smartcar_bringup smartcar_vision smartcar_tools

write_competition_env_snapshot
echo "Prepared competition environment snapshot: $COMPETITION_ENV_SNAPSHOT"
